name: flutter_application_2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  auto_route: ^10.0.1
  injectable: ^2.5.0
  intl: ^0.20.2
  intl_utils: ^2.8.10
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  collection: ^1.19.1
  syncfusion_flutter_charts: ^29.2.4
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3 
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5


flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/app/
    - assets/icons/foods/dairy/
    - assets/icons/foods/fruits/
    - assets/icons/foods/grains-pulses-beans/
    - assets/icons/foods/nuts-oils-spreads/
    - assets/icons/foods/protein/
    - assets/icons/foods/vegetables/
    - assets/icons/clothes/accessory/
    - assets/icons/clothes/bottom/
    - assets/icons/clothes/footwear/
    - assets/icons/clothes/headwear/
    - assets/icons/clothes/top/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
    - family: Lighthaus
      fonts:
        - asset: assets/fonts/Lighthaus/Lighthaus.ttf
        